trigger:
- master

pool:
  name: Default

steps:
- powershell: |
    choco install docfx -y
    docfx docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "docfx build"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: _site
    artifactName: site